CONTEXT = 'context'
MESSAGE = 'message'
CATALOG = 'catalog'
BPP_DESCRIPTOR = 'bpp/descriptor'
BPP_PROVIDERS = 'bpp/providers'
BPP_FULFILLMENTS = 'bpp/fulfillments'
BPP_CATEGORIES = 'bpp/categories'
BPP_ID = 'bpp_id'
ITEMS = 'items'
ID = 'id'
DESCRIPTOR = 'descriptor'
LOCATIONS = 'locations'
GPS = 'gps'
LOCATION_ID = 'location_id'
CATEGORY_ID = 'category_id'
FULFILLMENT_ID = 'fulfillment_id'


#######################
BPP_DETAILS = 'bpp_details'
PROVIDER_DETAILS = 'provider_details'
LOCATION_DETAILS = 'location_details'
CATEGORY_DETAILS = 'category_details'
FULFILLMENT_DETAILS = 'fulfillment_details'

